name: nlp_project
dependencies:
  - python = 3.9
  - scikit-learn
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - pip
  - pip:
    - revChatGPT
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyter-resource-usage
  - nodejs
  - widgetsnbextension